# Generated by Django 5.1.5 on 2025-02-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno_Motors', '0002_userdetails_remove_service_car_delete_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
