# Generated by Django 5.1.5 on 2025-03-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno_Motors', '0005_paymentmethod_alter_carcompany_name_useraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
