# Generated by Django 5.1.5 on 2025-04-11 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno_Motors', '0007_carlisting_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchase',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpurchase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userpurchase',
            name='car_part',
        ),
        migrations.RemoveField(
            model_name='userpurchase',
            name='user',
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.CreateModel(
            name='CarPartsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('payment_status', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inferno_Motors.carpart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inferno_Motors.userdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserPurchase',
        ),
    ]
