# Generated by Django 5.1.5 on 2025-04-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno_Motors', '0008_remove_userpurchase_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='user',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='CarListing',
        ),
    ]
