# Generated by Django 5.2.8 on 2025-11-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inferno_Motors', '0011_remove_purchaserequest_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
